import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
      <div className="Container">
      
        <Navbar/>
       {children}
       <Footer/>
       </div>
       </AppRouterCacheProvider>
        </body>
    </html>
  )
}
